# Import Packages

In [18]:
import pandas as Endy_pd
import numpy as Endy_np

# Import Data CSV

In [19]:
Endy_data = Endy_pd.read_csv('Online Retail Data.csv', header = 0)
Endy_data

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [20]:
Endy_data = Endy_data[Endy_data['price'].between(0, 100, inclusive = 'right')].reset_index(drop = True)

# Binning Data

In [11]:
#Membuat banyak bins tertentu dengan panjang yang sama
Endy_df1 = Endy_data.copy()
kategori = ['Murah', 'Standar', 'Mahal']
Endy_df1['Bin 1'] = Endy_pd.cut(Endy_df1['price'], 3, labels = kategori, include_lowest = True)
Endy_df1

,order_id,product_code,product_name,quantity,order_date,price,customer_id,Bin 1
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Murah
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Murah
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Murah
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Murah
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Murah
...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Murah
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Murah
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Murah
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Murah
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Murah

In [21]:
#Kita Tentukan bins nya
Endy_df2 = Endy_data.copy()
jumlah_bin = Endy_np.linspace(min(Endy_data['price']), max(Endy_data['price']), 4)
kategori = ['Murah', 'Standar', 'Mahal']
Endy_df2['Bin 2'] = Endy_pd.cut(Endy_df2['price'], jumlah_bin, labels = kategori, include_lowest = True)
Endy_df2

,order_id,product_code,product_name,quantity,order_date,price,customer_id,Bin 2
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Murah
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Murah
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Murah
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Murah
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Murah
...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Murah
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Murah
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Murah
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Murah
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Murah

In [15]:
#Menggunakan bins tapi kita tentukan jaraknya
Endy_df3 = Endy_data.copy()

jarak_interval = Endy_pd.interval_range(start = min(Endy_data['price']), freq = 10, end = max(Endy_data['price']))
Endy_df3['Bin 3'] = Endy_pd.cut(Endy_data['price'], bins = jarak_interval, include_lowest = True)
Endy_df3

,order_id,product_code,product_name,quantity,order_date,price,customer_id,Bin 3
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,"(0.001, 10.001]"
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,"(0.001, 10.001]"
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,"(0.001, 10.001]"
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,"(0.001, 10.001]"
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,"(0.001, 10.001]"
...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,"(0.001, 10.001]"
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,"(0.001, 10.001]"
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,"(0.001, 10.001]"
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,"(0.001, 10.001]"
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,"(0.001, 10.001]"

In [16]:
#Membuat bin tapi interval nya kita tentukan
Endy_df4 = Endy_data.copy()
batas_bin = [0, 30, 80, 100]
kategori = ['Murah', 'Standar', 'Mahal']
Endy_df4['Bin 4'] = Endy_pd.cut(Endy_data['price'], bins = batas_bin, labels = kategori, include_lowest = True)
Endy_df4

,order_id,product_code,product_name,quantity,order_date,price,customer_id,Bin 4
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Murah
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Murah
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Murah
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Murah
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Murah
...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Murah
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Murah
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Murah
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Murah
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Murah

In [17]:
#Menentukan banyak data dalam bin
Endy_df5 = Endy_data.copy()
kategori = ['Murah', 'Standar', 'Mahal']
Endy_df5['Bin 5'] = Endy_pd.qcut(Endy_data['price'], q = 3, labels = kategori)
Endy_df5

,order_id,product_code,product_name,quantity,order_date,price,customer_id,Bin 5
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Mahal
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Mahal
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Mahal
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Murah
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Mahal
...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Murah
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Murah
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Mahal
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Murah
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Standar

# Case Statemaent

In [23]:
Endy_df6 = Endy_df2.copy()
Endy_df6['price_class'] = Endy_np.select(
    [(Endy_df6['product_name'].str.lower().str.contains('tea')) & (Endy_df6['price'] <= 2),
    (Endy_df6['product_name'].str.lower().str.contains('tea')) & (Endy_df6['price'].between(2, 4, inclusive = 'right')),
    (Endy_df6['product_name'].str.lower().str.contains('tea')) & (Endy_df6['price'] > 4),
    (Endy_df6['product_name'].str.lower().str.contains('coffee')) & (Endy_df6['price'] <= 3),
    (Endy_df6['product_name'].str.lower().str.contains('coffee')) & (Endy_df6['price'].between(3, 5, inclusive = 'right')),
    (Endy_df6['product_name'].str.lower().str.contains('coffee')) & (Endy_df6['price'] >5)],
    ['Teh Murah', 'Teh Standar', 'Teh Mahal', 'Kopi Murah', 'Kopi Standar', 'Kopi Mahal'],
    default = 'Dalam Pengerjaan'
)

Endy_df6

,order_id,product_code,product_name,quantity,order_date,price,customer_id,Bin 2,price_class
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0,Murah,Dalam Pengerjaan
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0,Murah,Dalam Pengerjaan
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0,Murah,Dalam Pengerjaan
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN,Murah,Dalam Pengerjaan
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN,Murah,Dalam Pengerjaan
...,...,...,...,...,...,...,...,...,...
457466,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN,Murah,Dalam Pengerjaan
457467,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN,Murah,Dalam Pengerjaan
457468,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN,Murah,Dalam Pengerjaan
457469,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN,Murah,Dalam Pengerjaan
457470,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN,Murah,Dalam Pengerjaan