# Import Packages

In [4]:
import pandas as Endy_pd
import numpy as Endy_np
from fast_ml.feature_selection import get_duplicate_features

# Import Data

In [9]:
Endy_data = Endy_pd.DataFrame({
    'Visitor Name': ['Ivan', 'Adhitya', 'Christ', 'Ivan', 'Daniel'],
    'Age': [25, 23, 18, 25, 25],
    'Event Name': ['Harmony Fest 2020', 'Soundscape Live 2021', 'Nova Concert 2022', 'Skyline Music Show 2023', 'Unity Sound Fest 2026'],
    'Ticket Sold Year': [2020, 2021, 2022, 2023, 2026],
    'Event Year': [2020, 2021, 2022, 2023, 2026],
    'Ticket Type': ['Gold', 'Silver', 'Bronze', 'Silver', 'Silver'],
    'Ticket Price': [1000000.0, 750000.0, 500000.0, 750000.0, 750000.0],
    'Reward Point': [400, 350, 800, 0, 250]
})

Endy_data['Age'] = Endy_data['Age'].astype('Int64')
Endy_data['Ticket Sold Year'] = Endy_data['Ticket Sold Year'].astype('Int64')
Endy_data['Event Year'] = Endy_data['Event Year'].astype('Int64')
Endy_data['Ticket Price'] = Endy_data['Ticket Price'].astype(float)
Endy_data['Reward Point'] = Endy_data['Reward Point'].astype('Int64')
Endy_data

,Visitor Name,Age,Event Name,Ticket Sold Year,Event Year,Ticket Type,Ticket Price,Reward Point
0,Ivan,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,400
1,Adhitya,23,Soundscape Live 2021,2021,2021,Silver,750000.0,350
2,Christ,18,Nova Concert 2022,2022,2022,Bronze,500000.0,800
3,Ivan,25,Skyline Music Show 2023,2023,2023,Silver,750000.0,0
4,Daniel,25,Unity Sound Fest 2026,2026,2026,Silver,750000.0,250

In [8]:
Endy_data2 = Endy_pd.DataFrame({
    'Visitor Name': ['Ivan', 'Adhitya', 'Christ', 'Ivan', 'Daniel'],
    'Age': [25, 23, 18, 25, 25],
    'Event Name': ['Harmony Fest 2020', 'Soundscape Live 2021', 'Nova Concert 2022', 'Harmony Fest 2020', 'Unity Sound Fest 2026'],
    'Ticket Sold Year': [2020, 2021, 2022, 2020, 2026],
    'Event Year': [2020, 2021, 2022, 2020, 2026],
    'Ticket Type': ['Gold', 'Silver', 'Bronze', 'Gold', 'Silver'],
    'Ticket Price': [1000000.0, 750000.0, 500000.0, 1000000.0, 750000.0],
    'Reward Point': [400, 350, 800, 400, 250]
})

Endy_data2['Age'] = Endy_data2['Age'].astype('Int64')
Endy_data2['Ticket Sold Year'] = Endy_data2['Ticket Sold Year'].astype('Int64')
Endy_data2['Event Year'] = Endy_data2['Event Year'].astype('Int64')
Endy_data2['Ticket Price'] = Endy_data2['Ticket Price'].astype(float)
Endy_data2['Reward Point'] = Endy_data2['Reward Point'].astype('Int64')
Endy_data2

,Visitor Name,Age,Event Name,Ticket Sold Year,Event Year,Ticket Type,Ticket Price,Reward Point
0,Ivan,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,400
1,Adhitya,23,Soundscape Live 2021,2021,2021,Silver,750000.0,350
2,Christ,18,Nova Concert 2022,2022,2022,Bronze,500000.0,800
3,Ivan,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,400
4,Daniel,25,Unity Sound Fest 2026,2026,2026,Silver,750000.0,250

# Olah Data

In [5]:
#Menyisakan yang pertama
Endy_first = Endy_data.copy()
Endy_first.drop_duplicates(subset = 'Visitor Name', keep = 'first', inplace = True)
Endy_first

,Visitor Name,Age,Event Name,Ticket Sold Year,Event Year,Ticket Type,Ticket Price,Reward Point
0,Ivan,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,400
1,Adhitya,23,Soundscape Live 2021,2021,2021,Silver,750000.0,350
2,Christ,18,Nova Concert 2022,2022,2022,Bronze,500000.0,800
4,Daniel,25,Unity Sound Fest 2026,2026,2026,Silver,750000.0,250

In [6]:
#Menyisakan yang terakhir
Endy_last = Endy_data.copy()
Endy_last.drop_duplicates(subset = 'Visitor Name', keep = 'last', inplace = True)
Endy_last

,Visitor Name,Age,Event Name,Ticket Sold Year,Event Year,Ticket Type,Ticket Price,Reward Point
1,Adhitya,23,Soundscape Live 2021,2021,2021,Silver,750000.0,350
2,Christ,18,Nova Concert 2022,2022,2022,Bronze,500000.0,800
3,Ivan,25,Skyline Music Show 2023,2023,2023,Silver,750000.0,0
4,Daniel,25,Unity Sound Fest 2026,2026,2026,Silver,750000.0,250

In [11]:
#Hapus semua yang duplikat
Endy_all = Endy_data.copy()
Endy_all.drop_duplicates(subset = 'Visitor Name', keep = False, inplace = True)
Endy_all

,Visitor Name,Age,Event Name,Ticket Sold Year,Event Year,Ticket Type,Ticket Price,Reward Point
1,Adhitya,23,Soundscape Live 2021,2021,2021,Silver,750000.0,350
2,Christ,18,Nova Concert 2022,2022,2022,Bronze,500000.0,800
4,Daniel,25,Unity Sound Fest 2026,2026,2026,Silver,750000.0,250

In [14]:
#Hapus duplikasi yang barisnya sama semua
Endy_sama = Endy_data2.copy()
Endy_sama.drop_duplicates(inplace = True)
Endy_sama

,Visitor Name,Age,Event Name,Ticket Sold Year,Event Year,Ticket Type,Ticket Price,Reward Point
0,Ivan,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,400
1,Adhitya,23,Soundscape Live 2021,2021,2021,Silver,750000.0,350
2,Christ,18,Nova Concert 2022,2022,2022,Bronze,500000.0,800
4,Daniel,25,Unity Sound Fest 2026,2026,2026,Silver,750000.0,250

In [14]:
#Menangani Duplikasi Kolom
Endy_kolom = Endy_data2.copy()

kolom_duplikat = get_duplicate_features(Endy_kolom)
print('Duplikat kolom: \n')
print(kolom_duplikat)

list_duplikat = kolom_duplikat.loc[kolom_duplikat['Desc'] == 'Duplicate Values', 'feature2'].to_list()
print('\n List Kolom Duplikasi Values')
print(list_duplikat)

print('\n Banyaknya Kolom sebelum penghapusan kolom duplikasi values: ' + str(Endy_kolom.shape[1]))
Endy_kolom.drop(columns = list_duplikat, inplace = True)
print('Banyaknya kolom setelah penghapusan kolom duplikasi values: ' + str(Endy_kolom.shape[1]))
Endy_kolom

Duplikat kolom:

               Desc          feature1          feature2
0  Duplicate Values  Ticket Sold Year        Event Year
1   Duplicate Index      Visitor Name        Event Name
2   Duplicate Index      Visitor Name  Ticket Sold Year
3   Duplicate Index      Visitor Name        Event Year
4   Duplicate Index      Visitor Name      Reward Point
5   Duplicate Index        Event Name  Ticket Sold Year
6   Duplicate Index        Event Name        Event Year
7   Duplicate Index        Event Name      Reward Point
8   Duplicate Index  Ticket Sold Year      Reward Point
9   Duplicate Index       Ticket Type      Ticket Price

 List Kolom Duplikasi Values
['Event Year']

 Banyaknya Kolom sebelum penghapusan kolom duplikasi values: 8
Banyaknya kolom setelah penghapusan kolom duplikasi values: 7

,Visitor Name,Age,Event Name,Ticket Sold Year,Ticket Type,Ticket Price,Reward Point
0,Ivan,25,Harmony Fest 2020,2020,Gold,1000000.0,400
1,Adhitya,23,Soundscape Live 2021,2021,Silver,750000.0,350
2,Christ,18,Nova Concert 2022,2022,Bronze,500000.0,800
3,Ivan,25,Harmony Fest 2020,2020,Gold,1000000.0,400
4,Daniel,25,Unity Sound Fest 2026,2026,Silver,750000.0,250

In [16]:
#Menangani Duplikasi Kolom
Endy_index = Endy_data2.copy()

kolom_dupin = get_duplicate_features(Endy_index)
print('Duplikat kolom: \n')
print(kolom_dupin)

list_dupin = kolom_dupin.loc[kolom_dupin['Desc'] == 'Duplicate Index', 'feature2'].to_list()
print('\n List Kolom Duplikasi Index')
print(list_dupin)

print('\n Banyaknya Kolom sebelum penghapusan kolom duplikasi Index: ' + str(Endy_index.shape[1]))
Endy_index.drop(columns = list_dupin, inplace = True)
print('Banyaknya kolom setelah penghapusan kolom duplikasi Index: ' + str(Endy_index.shape[1]))
Endy_index

Duplikat kolom:

               Desc          feature1          feature2
0  Duplicate Values  Ticket Sold Year        Event Year
1   Duplicate Index      Visitor Name        Event Name
2   Duplicate Index      Visitor Name  Ticket Sold Year
3   Duplicate Index      Visitor Name        Event Year
4   Duplicate Index      Visitor Name      Reward Point
5   Duplicate Index        Event Name  Ticket Sold Year
6   Duplicate Index        Event Name        Event Year
7   Duplicate Index        Event Name      Reward Point
8   Duplicate Index  Ticket Sold Year      Reward Point
9   Duplicate Index       Ticket Type      Ticket Price

 List Kolom Duplikasi Index
['Event Name', 'Ticket Sold Year', 'Event Year', 'Reward Point', 'Ticket Sold Year', 'Event Year', 'Reward Point', 'Reward Point', 'Ticket Price']

 Banyaknya Kolom sebelum penghapusan kolom duplikasi Index: 8
Banyaknya kolom setelah penghapusan kolom duplikasi Index: 3

  Visitor Name  Age Ticket Type
0         Ivan   25        Gold
1      Adhitya   23      Silver
2       Christ   18      Bronze
3         Ivan   25        Gold
4       Daniel   25      Silver

In [17]:
Endy_data2

,Visitor Name,Age,Event Name,Ticket Sold Year,Event Year,Ticket Type,Ticket Price,Reward Point
0,Ivan,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,400
1,Adhitya,23,Soundscape Live 2021,2021,2021,Silver,750000.0,350
2,Christ,18,Nova Concert 2022,2022,2022,Bronze,500000.0,800
3,Ivan,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,400
4,Daniel,25,Unity Sound Fest 2026,2026,2026,Silver,750000.0,250