# Import Packages

In [7]:
import pandas as Endy_pd
import numpy as Endy_np

# Import Data

In [10]:
Endy_data = Endy_pd.DataFrame({'Visitor_name': ['Ivan', 'Denil', Endy_np.nan],
                             'Event_name': ['Rock Concert 2022', 'Jazz Festifal 2021', 'Pop Party 2024'],
                             'Ticket_sold_year': [2022, Endy_np.nan, 2024],
                             'Event_year': [2022, 2021, 2024],
                             'Ticket_type': ['Gold', 'Silver', 'Bronze'],
                             'Ticket_price': [1000000.0, 750000.0, 500000.0]})

Endy_data['Ticket_sold_year'] = Endy_data['Ticket_sold_year'].astype('Int64')
Endy_data['Event_year'] = Endy_data['Event_year'].astype('Int64')
Endy_data['Ticket_price'] = Endy_data['Ticket_price'].astype(float)
Endy_data

,Visitor_name,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price
0,Ivan,Rock Concert 2022,2022,2022,Gold,1000000.0
1,Denil,Jazz Festifal 2021,<NA>,2021,Silver,750000.0
2,NaN,Pop Party 2024,2024,2024,Bronze,500000.0

In [11]:
Endy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Visitor_name      2 non-null      object
 1   Event_name        3 non-null      object
 2   Ticket_sold_year  2 non-null      Int64
 3   Event_year        3 non-null      Int64
 4   Ticket_type       3 non-null      object
 5   Ticket_price      3 non-null      float64
dtypes: Int64(2), float64(1), object(3)
memory usage: 282.0+ bytes

In [25]:
Endy_data2 = Endy_pd.DataFrame({
    'Visitor_name': ['Andy', 'Ivan', 'Andhitya', 'Messi', 'Christ'],
    'Age': [25, Endy_np.nan, 32, 25, 19],
    'Event_name': ['Harmony Fest 2020', 'Skyline Music Show 2023', 'Vibrance Concert 2024', 'Zenith Music Festival 2025', 'Unity Sound Fest 2026'],
    'Ticket_sold_year': [2020, 2023, 2024, 2025, 2026],
    'Event_year': [2020, 2023, 2024, 2025, 2026],
    'Ticket_type': ['Gold', 'Bronze', 'Platinum', 'Gold', 'Silver'],
    'Ticket_price': [1000000.0, 500000.0, 2500000.0, 750000.0, 1000000.0],
    'Reward_point': [600, 300, 750, Endy_np.nan, 450]
})

Endy_data2['Age'] = Endy_data2['Age'].astype('Int64')
Endy_data2['Ticket_sold_year'] = Endy_data2['Ticket_sold_year'].astype('Int64')
Endy_data2['Event_year'] = Endy_data2['Event_year'].astype('Int64')
Endy_data2['Reward_point'] = Endy_data2['Reward_point'].astype('Int64')
Endy_data2['Ticket_price'] = Endy_data2['Ticket_price'].astype(float)
Endy_data2

,Visitor_name,Age,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price,Reward_point
0,Andy,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,600
1,Ivan,<NA>,Skyline Music Show 2023,2023,2023,Bronze,500000.0,300
2,Andhitya,32,Vibrance Concert 2024,2024,2024,Platinum,2500000.0,750
3,Messi,25,Zenith Music Festival 2025,2025,2025,Gold,750000.0,<NA>
4,Christ,19,Unity Sound Fest 2026,2026,2026,Silver,1000000.0,450

In [26]:
Endy_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Visitor_name      5 non-null      object
 1   Age               4 non-null      Int64
 2   Event_name        5 non-null      object
 3   Ticket_sold_year  5 non-null      Int64
 4   Event_year        5 non-null      Int64
 5   Ticket_type       5 non-null      object
 6   Ticket_price      5 non-null      float64
 7   Reward_point      4 non-null      Int64
dtypes: Int64(4), float64(1), object(3)
memory usage: 472.0+ bytes

# Olah Data

### Hapus data

In [27]:
#Jika kita ingin meng-drop yang ada NaN
Endy_data.dropna()

,Visitor_name,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price
0,Ivan,Rock Concert 2022,2022,2022,Gold,1000000.0

In [13]:
#Menghapus kolom
Endy_data.drop(columns = ['Visitor_name', 'Ticket_sold_year'])

           Event_name  Event_year Ticket_type  Ticket_price
0   Rock Concert 2022        2022        Gold     1000000.0
1  Jazz Festifal 2021        2021      Silver      750000.0
2      Pop Party 2024        2024      Bronze      500000.0

### Pengisian Data

In [28]:
#Mengisi NA pada reward point berdasarkan informasi yang ada pada tabel
Endy_data2['Reward_point'] = Endy_data2['Reward_point'].fillna(600)
Endy_data2

,Visitor_name,Age,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price,Reward_point
0,Andy,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,600
1,Ivan,<NA>,Skyline Music Show 2023,2023,2023,Bronze,500000.0,300
2,Andhitya,32,Vibrance Concert 2024,2024,2024,Platinum,2500000.0,750
3,Messi,25,Zenith Music Festival 2025,2025,2025,Gold,750000.0,600
4,Christ,19,Unity Sound Fest 2026,2026,2026,Silver,1000000.0,450

In [29]:
#Mengisi NA dengan Mean
Endy_data2_mean = Endy_data2.copy()
Endy_data2_mean['Age'] = Endy_data2_mean['Age'].fillna(Endy_data2_mean['Age'].mean().round())
Endy_data2_mean

,Visitor_name,Age,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price,Reward_point
0,Andy,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,600
1,Ivan,25,Skyline Music Show 2023,2023,2023,Bronze,500000.0,300
2,Andhitya,32,Vibrance Concert 2024,2024,2024,Platinum,2500000.0,750
3,Messi,25,Zenith Music Festival 2025,2025,2025,Gold,750000.0,600
4,Christ,19,Unity Sound Fest 2026,2026,2026,Silver,1000000.0,450

round() karena umur tidak ada yang berkoma, selalu bilangan bulat

In [30]:
#Mengisi nilai NA dengan Median
Endy_data2_med = Endy_data2.copy()
Endy_data2_med['Age'] = Endy_data2_med['Age'].fillna(Endy_data2_med['Age'].median())
Endy_data2_med

,Visitor_name,Age,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price,Reward_point
0,Andy,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,600
1,Ivan,25,Skyline Music Show 2023,2023,2023,Bronze,500000.0,300
2,Andhitya,32,Vibrance Concert 2024,2024,2024,Platinum,2500000.0,750
3,Messi,25,Zenith Music Festival 2025,2025,2025,Gold,750000.0,600
4,Christ,19,Unity Sound Fest 2026,2026,2026,Silver,1000000.0,450

In [32]:
#Mengisi nilai NA dengan Modus
Endy_data2_mod = Endy_data2.copy()
Endy_data2_mod['Age'] = Endy_data2_mod['Age'].fillna(Endy_data2_mod['Age'].mode()[0])
Endy_data2_mod

,Visitor_name,Age,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price,Reward_point
0,Andy,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,600
1,Ivan,25,Skyline Music Show 2023,2023,2023,Bronze,500000.0,300
2,Andhitya,32,Vibrance Concert 2024,2024,2024,Platinum,2500000.0,750
3,Messi,25,Zenith Music Festival 2025,2025,2025,Gold,750000.0,600
4,Christ,19,Unity Sound Fest 2026,2026,2026,Silver,1000000.0,450

In [33]:
#Mengisi NA dengan nilai sebelumnya
Endy_data2_ffill = Endy_data2.copy()
Endy_data2_ffill['Age'] = Endy_data2_ffill['Age'].fillna(method = 'ffill')
Endy_data2_ffill

C:\Users\Acer\AppData\Local\Temp\ipykernel_6564\858834116.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Endy_data2_ffill['Age'] = Endy_data2_ffill['Age'].fillna(method = 'ffill')

,Visitor_name,Age,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price,Reward_point
0,Andy,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,600
1,Ivan,25,Skyline Music Show 2023,2023,2023,Bronze,500000.0,300
2,Andhitya,32,Vibrance Concert 2024,2024,2024,Platinum,2500000.0,750
3,Messi,25,Zenith Music Festival 2025,2025,2025,Gold,750000.0,600
4,Christ,19,Unity Sound Fest 2026,2026,2026,Silver,1000000.0,450

In [34]:
#Mengisi Nilai NA dengan Nilai Setelahnya
Endy_data2_bfill = Endy_data2.copy()
Endy_data2_bfill['Age'] = Endy_data2_bfill['Age'].fillna(method = 'bfill')
Endy_data2_bfill

C:\Users\Acer\AppData\Local\Temp\ipykernel_6564\3477443846.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  Endy_data2_bfill['Age'] = Endy_data2_bfill['Age'].fillna(method = 'bfill')

,Visitor_name,Age,Event_name,Ticket_sold_year,Event_year,Ticket_type,Ticket_price,Reward_point
0,Andy,25,Harmony Fest 2020,2020,2020,Gold,1000000.0,600
1,Ivan,32,Skyline Music Show 2023,2023,2023,Bronze,500000.0,300
2,Andhitya,32,Vibrance Concert 2024,2024,2024,Platinum,2500000.0,750
3,Messi,25,Zenith Music Festival 2025,2025,2025,Gold,750000.0,600
4,Christ,19,Unity Sound Fest 2026,2026,2026,Silver,1000000.0,450