# Import Packages

In [7]:
import pandas as Endy_pd
import numpy as Endy_np
from fast_ml.feature_selection import get_duplicate_features

# Proses

In [10]:
#Mengubah suatu kolom menjadi numerik
Endy_df = Endy_pd.DataFrame({'Point': ['200', '100']})
Endy_df.info()

Endy_df['Point'] = Endy_df['Point'].astype(int)
Endy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Point   2 non-null      object
dtypes: object(1)
memory usage: 148.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Point   2 non-null      int64
dtypes: int64(1)
memory usage: 148.0 bytes

In [14]:
#Mengubah string menjadi date time
Endy_df1 = Endy_pd.DataFrame({'Tanggal': ['20220824', '20261226']})
Endy_df1.info()

Endy_df1['Tanggal'] = Endy_pd.to_datetime(Endy_df1['Tanggal'], format = '%Y%m%d')
Endy_df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Tanggal  2 non-null      object
dtypes: object(1)
memory usage: 148.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Tanggal  2 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 148.0 bytes

In [17]:
#Mengangani teks yang tidak konsisten
Endy_df2 = Endy_pd.DataFrame({'Menu': ['ICE TEA', 'Ice Tea', 'ice tea']})

#1. Mengubah menjadi kecil semua
Endy_df2['Menu'] = Endy_df2['Menu'].str.lower()
Endy_df2

      Menu
0  ice tea
1  ice tea
2  ice tea

In [18]:
#2 Mengubah menjadi besar semua
Endy_df2['Menu'] = Endy_df2['Menu'].str.upper()
Endy_df2

      Menu
0  ICE TEA
1  ICE TEA
2  ICE TEA

In [19]:
#3 Menjadi huruf besar diawal kata
Endy_df2['Menu'] = Endy_df2['Menu'].str.title()
Endy_df2

      Menu
0  Ice Tea
1  Ice Tea
2  Ice Tea

In [24]:
#Menangani Spas yang tidak perlu
Endy_df3 = Endy_pd.DataFrame({'Menu': ['  Ice Tea  ', '  Ice Tea', 'Ice Tea  ']})
print(Endy_df3)

Endy_df3['Menu'] = Endy_df3['Menu'].str.strip()
print('\n')
print(Endy_df3)

          Menu
0    Ice Tea
1      Ice Tea
2    Ice Tea


      Menu
0  Ice Tea
1  Ice Tea
2  Ice Tea

In [26]:
#Menghapus string yang tidak perlu
Endy_df4 = Endy_pd.DataFrame({'Produk':['ICE TEA (SOLD PER 1 GLASS)','RAINBOW CAKE (SOLD PER 1 SLICE)']})
print(Endy_df4)

Endy_df4['Produk'] = Endy_df4['Produk'].str.replace(r' \(SOLD.*', '', regex = True)
print(Endy_df4)

                            Produk
0       ICE TEA (SOLD PER 1 GLASS)
1  RAINBOW CAKE (SOLD PER 1 SLICE)
         Produk
0       ICE TEA
1  RAINBOW CAKE

In [29]:
#Mengubah sebuah string
Endy_df5 = Endy_pd.DataFrame({'Alamat': ['jl. Baru', 'jl. Indah']})
print(Endy_df5)

Endy_df5['Alamat'] = Endy_df5['Alamat'].str.replace(r'jl.* ', 'Jalan ', regex = True)
print(Endy_df5)

      Alamat
0   jl. Baru
1  jl. Indah
        Alamat
0   Jalan Baru
1  Jalan Indah