# Import Packages

In [1]:
import pandas as Endy_pd

# Import File

In [3]:
Endy_data = Endy_pd.read_csv('Online Retail Data.csv', header = 0)
Endy_data

,order_id,product_code,product_name,quantity,order_date,price,customer_id
0,493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
1,C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
2,493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
3,493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
4,493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...,...
461768,539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
461769,539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
461770,539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
461771,539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
461772,539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

# Akses Lokasi

### Akses Bilangan Bulat

variabel_data_frame.iloc[index_row, index_coloumn] ## Khusus bilangan bulat

In [12]:
#Akses satu baris dan kolom saja
Endy_data.iloc[100, 4]

'2010-01-04 12:30:00'

In [13]:
#Akses beberapa baris dan kolom menggunakan list
Endy_data.iloc[[100, 200, 300], [4, 5, 6]]

              order_date  price  customer_id
100  2010-01-04 12:30:00   3.75      14680.0
200  2010-01-04 12:57:00   2.95      13206.0
300  2010-01-04 13:39:00   1.95      14527.0

In [14]:
#Akses beberapa baris dan kolom menggunakan indeks
Endy_data.iloc[100:201, 3:7]

     quantity           order_date  price  customer_id
100         1  2010-01-04 12:30:00   3.75      14680.0
101         1  2010-01-04 12:30:00   4.95      14680.0
102         2  2010-01-04 12:30:00   3.75      14680.0
103         1  2010-01-04 12:30:00   4.25      14680.0
104         5  2010-01-04 12:30:00   7.95      14680.0
..        ...                  ...    ...          ...
196         8  2010-01-04 12:57:00   1.25      13206.0
197        12  2010-01-04 12:57:00   0.65      13206.0
198        24  2010-01-04 12:57:00   1.25      13206.0
199        12  2010-01-04 12:57:00   0.85      13206.0
200         6  2010-01-04 12:57:00   2.95      13206.0

[101 rows x 4 columns]

In [16]:
#Akses beberapa baris dan kolom menggunakan indeks (slicing)
Endy_data.iloc[:41, 3:]

    quantity           order_date  price  customer_id
0          5  2010-01-04 09:24:00   4.50      12346.0
1         -1  2010-01-04 09:43:00   4.25      14590.0
2          5  2010-01-04 09:53:00   4.50      12346.0
3          1  2010-01-04 09:54:00   0.85          NaN
4          1  2010-01-04 09:54:00   3.75          NaN
5          1  2010-01-04 09:54:00   0.85          NaN
6         36  2010-01-04 10:28:00   2.55      14590.0
7         12  2010-01-04 10:28:00   4.25      14590.0
8          2  2010-01-04 10:28:00   2.55      14590.0
9          2  2010-01-04 10:28:00   4.25      14590.0
10        12  2010-01-04 10:28:00   6.95      14590.0
11        24  2010-01-04 10:28:00   2.10      14590.0
12        -3  2010-01-04 10:33:00   7.95      14590.0
13        -1  2010-01-04 10:41:00   3.39      16550.0
14         4  2010-01-04 10:43:00   5.95      13287.0
15         2  2010-01-04 10:43:00   9.95      13287.0
16         4  2010-01-04 10:43:00   4.95      13287.0
17         6  2010-01-04 10:43:00   2.55      13287.0
18         6  2010-01-04 10:43:00   2.25      13287.0
19         6  2010-01-04 10:43:00   2.25      13287.0
20        12  2010-01-04 10:43:00   1.49      13287.0
21        12  2010-01-04 10:43:00   1.25      13287.0
22        12  2010-01-04 10:43:00   0.85      13287.0
23        12  2010-01-04 10:43:00   0.85      13287.0
24        12  2010-01-04 10:43:00   0.85      13287.0
25         6  2010-01-04 10:43:00   2.55      13287.0
26         6  2010-01-04 10:43:00   1.25      13287.0
27         4  2010-01-04 10:43:00   4.25      13287.0
28        12  2010-01-04 10:43:00   1.25      13287.0
29         2  2010-01-04 10:43:00   7.95      13287.0
30         2  2010-01-04 10:43:00   4.25      13287.0
31         2  2010-01-04 10:43:00   7.95      13287.0
32         1  2010-01-04 11:15:00   5.95      16550.0
33         1  2010-01-04 11:15:00   7.95      16550.0
34         6  2010-01-04 11:15:00   1.25      16550.0
35         2  2010-01-04 11:15:00   3.95      16550.0
36         4  2010-01-04 11:15:00   2.95      16550.0
37         6  2010-01-04 11:15:00   2.95      16550.0
38         6  2010-01-04 11:15:00   0.85      16550.0
39         6  2010-01-04 11:15:00   1.65      16550.0
40        10  2010-01-04 11:15:00   1.45      16550.0

In [18]:
#Akses baris dan kolom dari belakang
Endy_data.iloc[-1, -1] #output aneh karena bukan int

np.float64(nan)

In [19]:
#Akses beberapa baris dan kolom dari belakang
Endy_data.iloc[-100:, :-3]

       order_id product_code                        product_name  quantity
461673   539988        22568               FELTCRAFT CUSHION OWL         1
461674   539988        22569         FELTCRAFT CUSHION BUTTERFLY         1
461675   539988        22570            FELTCRAFT CUSHION RABBIT         1
461676   539988        21380       WOODEN HAPPY BIRTHDAY GARLAND         2
461677   539988        21381  MINI WOODEN HAPPY BIRTHDAY GARLAND         2
...         ...          ...                                 ...       ...
461768   539991        21618      4 WILDFLOWER BOTANICAL CANDLES         1
461769   539991        72741               GRAND CHOCOLATECANDLE         4
461770   539992        21470       FLOWER VINE RAFFIA FOOD COVER         1
461771   539992        22258             FELT FARM ANIMAL RABBIT         1
461772   539992        21155               RED RETROSPOT PEG BAG         1

[100 rows x 4 columns]

### Akses Selain Bilangan Bulat

In [23]:
Endy_data_non = Endy_data.copy()
Endy_data_non.set_index('order_id', inplace = True)
Endy_data_non

,product_code,product_name,quantity,order_date,price,customer_id
order_id,,,,,,
493410,TEST001,This is a test product.,5,2010-01-04 09:24:00,4.50,12346.0
C493411,21539,RETRO SPOTS BUTTER DISH,-1,2010-01-04 09:43:00,4.25,14590.0
493412,TEST001,This is a test product.,5,2010-01-04 09:53:00,4.50,12346.0
493413,21724,PANDA AND BUNNIES STICKER SHEET,1,2010-01-04 09:54:00,0.85,NaN
493413,84578,ELEPHANT TOY WITH BLUE T-SHIRT,1,2010-01-04 09:54:00,3.75,NaN
...,...,...,...,...,...,...
539991,21618,4 WILDFLOWER BOTANICAL CANDLES,1,2010-12-23 16:49:00,1.25,NaN
539991,72741,GRAND CHOCOLATECANDLE,4,2010-12-23 16:49:00,1.45,NaN
539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [32]:
#Akses Baris saja
Endy_data_non.loc['539992']

,product_code,product_name,quantity,order_date,price,customer_id
order_id,,,,,,
539992,21470,FLOWER VINE RAFFIA FOOD COVER,1,2010-12-23 17:41:00,3.75,NaN
539992,22258,FELT FARM ANIMAL RABBIT,1,2010-12-23 17:41:00,1.25,NaN
539992,21155,RED RETROSPOT PEG BAG,1,2010-12-23 17:41:00,2.10,NaN

In [33]:
#Akses satu baris dan kolom
Endy_data_non.loc['C493411', 'product_name']

'RETRO SPOTS BUTTER DISH'

In [34]:
#Akses kolom
Endy_data_non.loc[:, 'quantity']

order_id
493410     5
C493411   -1
493412     5
493413     1
493413     1
          ..
539991     1
539991     4
539992     1
539992     1
539992     1
Name: quantity, Length: 461773, dtype: int64